### ISSUE TITLE
Rpc interface

### ISSUE THREAD

**Issue by BaerCali** [BaerChain/cpp-lsac#2]
Want to query the block height locally, how to get the height through curl?

**Comment by blizzardbaer** [comment]
u can read this[https://github.com/BaerChain/cpp-lsac/wiki/BaerChain-coupling-system-RPC-interface](url)

**Comment by boltbaer** [comment]
Use --http_port to specify the port，and curl -X POST --data '{"jsonrpc":"2.0","method":"brc_blockNumber","params":[],"id":17}' http://0.0.0.0:0 , your ip and port
