### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by BXHash** [BaerChain/cpp-lsac#20]
How to get install_deps.bat?

**Comment by BXHash** [comment]
No reply?

**Comment by rdsnbaer** [comment]
Do you want to compile on Windows?

**Comment by BXHash** [comment]
thanks your reply!  yes!

**Comment by rdsnbaer** [comment]
The community will provide Windows compiler scripts in the future

**Comment by BXHash** [comment]
thanks， waiting for your news
